// Stub types for convex codegen
// Real types are generated by `bun convex dev --once`

export declare function query<Args extends Record<string, any>, Returns>(config: {
  args: Args;
  handler: (ctx: any, args: any) => Promise<Returns>;
}): any;

export declare function mutation<Args extends Record<string, any>, Returns>(config: {
  args: Args;
  handler: (ctx: any, args: any) => Promise<Returns>;
}): any;

export declare function action<Args extends Record<string, any>, Returns>(config: {
  args: Args;
  handler: (ctx: any, args: any) => Promise<Returns>;
}): any;

export type QueryCtx = any;
export type MutationCtx = any;
